#!/bin/bash

# git clone https://github.com/Islandora-Devops/islandora-playbook.git

# check for claw.dev in hostname!

# after ansible-galaxy install -r requirements.yml
# correct password in 
# roles/external/Islandora-Devops.fcrepo/defaults/main.yml


# variables to be set
HOSTNAME=
PASSWORD=""
TOKEN=""
CONFIG_ADDS_SOURCES=./
ISLANDORA_PLAYBOOK_DIR=./islandora-playbook/inventory/production
SSH_KEY_PATH=


# default variables, do not touch
SOURCE_HOSTNAME=127.0.0.1
SOURCE_ANSIBLE_PORT='ansible_port=2222'
APACHE_PORT=80

sed -i "s/ islandora/ $PASSWORD/" ${ISLANDORA_PLAYBOOK_DIR}/group_vars/all/passwords.yml 

cat ${CONFIG_ADDS_SOURCES}/islandora-config-lines-crayfish.txt >> ${ISLANDORA_PLAYBOOK_DIR}/group_vars/crayfish.yml 
sed -i "s!example.org!${HOSTNAME}!" ${ISLANDORA_PLAYBOOK_DIR}/group_vars/crayfish.yml

cat ${CONFIG_ADDS_SOURCES}/islandora-config-lines-karaf.txt >> ${ISLANDORA_PLAYBOOK_DIR}/group_vars/karaf.yml
sed -i "s/changeme/${TOKEN}/" ${ISLANDORA_PLAYBOOK_DIR}/group_vars/karaf.yml
sed -i "s/example.org/${HOSTNAME}/" ${ISLANDORA_PLAYBOOK_DIR}/group_vars/karaf.yml

cat ${CONFIG_ADDS_SOURCES}/islandora-config-lines-tomcat.txt >> ${ISLANDORA_PLAYBOOK_DIR}/group_vars/tomcat.yml
sed -i "s/example.org/${HOSTNAME}/" ${ISLANDORA_PLAYBOOK_DIR}/group_vars/tomcat.yml


sed -i "s/apache_listen_port: 8000/apache_listen_port: ${APACHE_PORT}/" ${ISLANDORA_PLAYBOOK_DIR}/group_vars/webserver/apache.yml
sed -i "s!{{ hostvars\[groups\['webserver'\]\[0\]\].ansible_host }}!${HOSTNAME}!" ${ISLANDORA_PLAYBOOK_DIR}/group_vars/webserver/drupal.yml
sed -i "s!{{ hostvars\[groups\['tomcat'\]\[0\]\].ansible_host }}!${HOSTNAME}!" ${ISLANDORA_PLAYBOOK_DIR}/group_vars/webserver/drupal.yml
sed -i "s!{{ hostvars\[groups\['tomcat'\]\[0\]\].ansible_host }}!${HOSTNAME}!" ${ISLANDORA_PLAYBOOK_DIR}/group_vars/webserver/general.yml
echo "matomo_site_url: ${HOSTNAME}" >> ${ISLANDORA_PLAYBOOK_DIR}/group_vars/webserver/general.yml
sed -i "s/127.0.0.1/${HOSTNAME}/g" ${ISLANDORA_PLAYBOOK_DIR}/hosts
sed -i "s/2222/22 ansible_user=root/" ${ISLANDORA_PLAYBOOK_DIR}/hosts
sed -i "s!.vagrant/machines/default/virtualbox/private_key!${SSH_KEY_PATH}!" ${ISLANDORA_PLAYBOOK_DIR}/hosts
sed -i "s/claw.dev/${HOSTNAME}/" ${ISLANDORA_PLAYBOOK_DIR}/group_vars/webserver/apache.yml
sed -i "s/claw.dev/${HOSTNAME}/" ${ISLANDORA_PLAYBOOK_DIR}/group_vars/webserver/drupal.yml
#sed -i "s/\(login_.*\)/#\1/" ${ISLANDORA_PLAYBOOK_DIR}/roles/external/Islandora-Devops.fcrepo/tasks/db-mysql.yml
