broker_url: 'tcp://localhost:61613'
jwt_expiry: '+2 hour'
gemini_url: 'https://dan-demo.phil.muni.cz:443/gemini'
gemini_pseudo_bundles:
  'islandora_object:node': 'islandora_object:node'
  'audio:media': 'audio:media'
  'file:media': 'file:media'
  'image:media': 'image:media'
  'video:media': 'video:media'
_core:
  default_config_hash: XgeYJpPmZIOwE_nA73tYvFw-Rcj-HtlbNwfktqSVsaQ
langcode: cs
