---
# DEPRECATED: the actual playbook for islandora preinstall has been moved to the 
# https://github.com/ArtsFacultyMU/digitalia-ansible repository
# check then documentation on 
# https://ucnmuni.sharepoint.com/:w:/r/teams/dariah-ffmu/Sdilene%20dokumenty/08_INFRASTRUKTURA%20DIGITALIA/Digitalia_infrastructure_maintenance_manual.docx?d=w1ebbde32e1164393951b4e6976e6bd73&csf=1&web=1&e=YUY6xq
- name: Islandora preinstallation set up
  # this playbook should be run on server _before_ installing Islandora via official playbook
  hosts: all
  remote_user: root

  tasks:
    - name: Create islandora user
      ansible.builtin.user:
        name: islandora
        password: "{{ islandora_password | password_hash('sha512', 'mysecretsalt') }}"
        groups: islandora,sudo
        shell: "/bin/bash"


    # needs collection ansible.posix
    # install via ansible-galaxy collection install ansible.posix
    # see https://docs.ansible.com/ansible/latest/collections/ansible/posix/authorized_key_module.html
    - name: Copy ssh key
      ansible.posix.authorized_key:
        user: islandora
        state: present
        exclusive: true
          #        key: "{{ lookup('file', '/home/krejvl/.ssh/id_rsa.pub') }}"
        key: '{{ item }}'
      with_file:
        - "{{ ansible_ssh_private_key_file }}.pub"
