label: 'Linked Agent'
description: 'Create new agents by adding terms to the <a href="/admin/structure/taxonomy/manage/person/overview">Person</a>, <a href="/admin/structure/taxonomy/manage/family/overview">Family</a>, or <a href="/admin/structure/taxonomy/manage/corporate_body/overview">Corporate Body</a> vocabularies.'
